### ISSUE TITLE
Script Contents

### ISSUE THREAD

**Issue by scottgarner** [processing/p5.js-video#1]
Just wanted to start a conversation about what should be covered in the script.

The first big question that comes to mind is whether this is geared towards people familiar with Processing that might want to experiment on the web or toward absolute beginners.

**Comment by shiffman** [comment]
I keep going back and forth, there are pros and cons to each.  In a way, making something for the existing Processing community would be easier for me since that's where I am coming from.  At the same time, that's a limiting audience.   Maybe we think of this as something for absolute beginners but we acknowledge and reference Processing?

A quick outline:
- Everything wants to teach you programming these days.
- Here's another thing.
- Drawing
- What code looks like, JS
- This came from Processing
- And now the web. . . 
- And more . . .
