### ISSUE TITLE
mouseX and mouseY default to 0,0 until mouse is moved

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-video#10]
@lmccart is this a p5.js bug or just the way things work?  I think this would be worth dealing with if we can.

**Comment by lmccart** [comment]
yes, it's initialized to 0,0 until mouse move. I think this is the same as processing behavior, but it feels weirder because your mouse is most likely somewhere on the page already.

I'm not sure there's an elegant way around this from the library end:
http://stackoverflow.com/questions/2601097/how-to-get-the-mouse-position-without-events-without-moving-the-mouse
this was a quick search though, I can keep looking.

but if we're talking hello p5.js you could initialized the mouse to the coordinates of the play button or however you start the show.

**Comment by scottgarner** [comment]
Ah, you're right. There's no way to get the position without an event.

Unfortunately, we can't just go by a play button's location in this case because it's a sketch started by a Popcorn event and the user will likely have moved their mouse to interact with the previous sketch.

Two workarounds might be:

1) Have a handler outside of the sketches that stores the mouse position, beginning with the initial play click.

2) Build it into Dan's explanation. Something like, "Now you can see that the circles are avoiding my head. If you move your mouse, they'll run away from that, too."

**Comment by lmccart** [comment]
Either seems to work. If there are many sketches where we want the mouse position from the start, the handler makes sense. Otherwise, option two sounds great, and I like the idea of the user taking over control
