### ISSUE TITLE
update p5.sound library

### ISSUE THREAD

**Issue by therewasaguy** [processing/p5.js-video#51]
There is a bug with sound on hello.p5js.org right now, as mentioned [here](https://github.com/scottgarner/p5.js-video/issues/47) and [here](https://github.com/processing/p5.js-sound/issues/106).

It is fixed in newer versions so the library.

If simply swapping it out for the [latest version](https://github.com/processing/p5.js-sound/blob/master/lib/p5.sound.js) doesn't work, I can look into it more

**Comment by scottgarner** [comment]
Thanks for the head's up, Jason. I'm crunching to deliver a project this week, but will look into this as soon as I get a chance.

**Comment by scottgarner** [comment]
I updated to the latest p5 and p5.sound. There had been a lot of API changes since the site launched—hopefully I made the right fixes.

Things seem to work, though I did notice an error on`sketch.remove();` in Chrome:

`p5.sound.min.js:4 Uncaught TypeError: Cannot read property 'disconnect' of undefined`
