### ISSUE TITLE
check angle direction for wind

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-video#9]

**Comment by shiffman** [comment]
https://github.com/scottgarner/p5.js-video/commit/38bcc0b8a642e399e158cd19be42373bad01334e @scottgarner I added:

```
    sketch.getElement("gauge").elt.style['-webkit-transform'] = 'rotate('+dir+'deg)';
```

in order for the rotation to show up in chrome.  The angle seems to be right for me now.   Can you confirm?

**Comment by scottgarner** [comment]
Oh, sorry! I think transform is supported without a prefix in Chrome Canary (which I'm using) and Safari 8.0 and probably not stock Chrome yet. We might have to add a few other prefixed versions for other browsers, too.

But the element rotation was fine for me, it was just that the vector in the sketch seemed incorrect without applying an offset. Like radians() or fromAngle() viewed right as 0 instead of up.

If you uncomment the drawVector stuff and remove the [90 degree offset](https://github.com/scottgarner/p5.js-video/blob/gh-pages/examples/flocking/sketch.js#L78-81) you can see what I mean.

**Comment by scottgarner** [comment]
Actually, it looks like we're okay with the element rotation because IE and Firefox now support transform without a prefix and -webkit will cover versions of Chrome, Safari and Opera that don't. 

And thank you for catching my dyslexic spelling of gauge!

**Comment by shiffman** [comment]
Ah, gotcha.  I don't think this is a bug, I think it's just that we are considering the 0 angle to mean different things.  Maybe it shouldn't be this, but my thought was a 2D vector with a direction of 0 should point to the right (i.e. along the x-axis).  I don't think it really matters for this particular example as long as we are consistent.

**Comment by scottgarner** [comment]
Oh, of course. Zero as right definitely seems correct for dealing with vectors, so the offset makes perfect sense.

It's odd that Processing.js explicitly defines zero as up for rotate(), but that's just a technicality, I think, since rotate() is always relative.

**Comment by shiffman** [comment]
Great!  Closing.
